# TCL File Generated by Component Editor 25.1
# Tue Dec 30 17:24:50 CST 2025
# DO NOT MODIFY


# 
# openc906_vjtag_dtm "openC906 DTM for Virtual JTAG" v1.0
#  2025.12.30.17:24:50
# openC906 DTM adapted to Altera Virtual JTAG
# 

# 
# request TCL package from ACDS 25.1
# 
package require -exact qsys 25.1


# 
# module openc906_vjtag_dtm
# 
set_module_property DESCRIPTION "openC906 DTM adapted to Altera Virtual JTAG"
set_module_property NAME openc906_vjtag_dtm
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property BSP_CPU false
set_module_property GROUP "Processors and Peripherals/Embedded Processors"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "openC906 DTM for Virtual JTAG"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0
set_module_property PRE_COMP_MODULE_ENABLED false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL tdt_dmi_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file tdt_apb_master.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/tdt_apb_master.v
add_fileset_file tdt_dmi.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/tdt_dmi.v
add_fileset_file tdt_dmi_define.h VERILOG_INCLUDE PATH C906_RTL_FACTORY/gen_rtl/tdt_dmi_define.h
add_fileset_file tdt_dmi_pulse_sync.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/tdt_dmi_pulse_sync.v
add_fileset_file tdt_dmi_rst_top.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/tdt_dmi_rst_top.v
add_fileset_file tdt_dmi_sync_dff.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/tdt_dmi_sync_dff.v
add_fileset_file tdt_dmi_top.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/tdt_dmi_top.v TOP_LEVEL_FILE
add_fileset_file tdt_dtm_chain.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/tdt_dtm_chain.v
add_fileset_file tdt_dtm_ctrl.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/tdt_dtm_ctrl.v
add_fileset_file tdt_dtm_idr.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/tdt_dtm_idr.v
add_fileset_file tdt_dtm_io.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/tdt_dtm_io.v
add_fileset_file tdt_dtm_top.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/tdt_dtm_top.v
add_fileset_file tdt_gated_clk_cell.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/tdt_gated_clk_cell.v
add_fileset_file tdt_define.h VERILOG_INCLUDE PATH C906_RTL_FACTORY/gen_rtl/tdt_define.h
add_fileset_file cpu_cfig.h VERILOG_INCLUDE PATH C906_RTL_FACTORY/gen_rtl/cpu_cfig.h


# 
# parameters
# 


# 
# display items
# 


# 
# connection point dtm
# 
add_interface dtm apb start
set_interface_property dtm associatedClock apbclk
set_interface_property dtm associatedReset apbrst
set_interface_property dtm enableConcurrentSubordinateAccess 0
set_interface_property dtm ENABLED true
set_interface_property dtm EXPORT_OF ""
set_interface_property dtm PORT_NAME_MAP ""
set_interface_property dtm CMSIS_SVD_VARIABLES ""
set_interface_property dtm SVD_ADDRESS_GROUP ""
set_interface_property dtm IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property dtm SV_INTERFACE_TYPE ""
set_interface_property dtm SV_INTERFACE_MODPORT_TYPE ""

add_interface_port dtm tdt_dmi_paddr paddr Output 12
add_interface_port dtm tdt_dmi_penable penable Output 1
add_interface_port dtm tdt_dmi_prdata prdata Input 32
add_interface_port dtm tdt_dmi_pready pready Input 1
add_interface_port dtm tdt_dmi_psel psel Output 1
add_interface_port dtm tdt_dmi_pslverr pslverr Input 1
add_interface_port dtm tdt_dmi_pwdata pwdata Output 32
add_interface_port dtm tdt_dmi_pwrite pwrite Output 1


# 
# connection point apbclk
# 
add_interface apbclk clock end
set_interface_property apbclk ENABLED true
set_interface_property apbclk EXPORT_OF ""
set_interface_property apbclk PORT_NAME_MAP ""
set_interface_property apbclk CMSIS_SVD_VARIABLES ""
set_interface_property apbclk SVD_ADDRESS_GROUP ""
set_interface_property apbclk IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property apbclk SV_INTERFACE_TYPE ""
set_interface_property apbclk SV_INTERFACE_MODPORT_TYPE ""

add_interface_port apbclk sys_apb_clk clk Input 1


# 
# connection point apbrst
# 
add_interface apbrst reset end
set_interface_property apbrst associatedClock apbclk
set_interface_property apbrst synchronousEdges DEASSERT
set_interface_property apbrst ENABLED true
set_interface_property apbrst EXPORT_OF ""
set_interface_property apbrst PORT_NAME_MAP ""
set_interface_property apbrst CMSIS_SVD_VARIABLES ""
set_interface_property apbrst SVD_ADDRESS_GROUP ""
set_interface_property apbrst IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property apbrst SV_INTERFACE_TYPE ""
set_interface_property apbrst SV_INTERFACE_MODPORT_TYPE ""

add_interface_port apbrst sys_apb_rst_b reset_n Input 1

