# TCL File Generated by Component Editor 25.1
# Tue Dec 30 17:06:45 CST 2025
# DO NOT MODIFY


# 
# openc906 "openc906" v1.0
#  2025.12.30.17:06:45
# Xuantie openC906
# 

# 
# request TCL package from ACDS 25.1
# 
package require -exact qsys 25.1


# 
# module openc906
# 
set_module_property DESCRIPTION "Xuantie openC906"
set_module_property NAME openc906
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property BSP_CPU true
set_module_property GROUP "Processors and Peripherals/Embedded Processors"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME openc906
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0
set_module_property PRE_COMP_MODULE_ENABLED false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL openC906
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file BUFGCE.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/BUFGCE.v
add_fileset_file aq_biu_apbif.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_biu_apbif.v
add_fileset_file aq_biu_read_channel.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_biu_read_channel.v
add_fileset_file aq_biu_req_arbiter.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_biu_req_arbiter.v
add_fileset_file aq_biu_top.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_biu_top.v
add_fileset_file aq_biu_write_channel.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_biu_write_channel.v
add_fileset_file aq_biu_wt_entry.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_biu_wt_entry.v
add_fileset_file aq_core.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_core.v
add_fileset_file aq_cp0_cache_inst.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_cp0_cache_inst.v
add_fileset_file aq_cp0_ext_csr.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_cp0_ext_csr.v
add_fileset_file aq_cp0_fence_inst.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_cp0_fence_inst.v
add_fileset_file aq_cp0_float_csr.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_cp0_float_csr.v
add_fileset_file aq_cp0_hpcp_csr.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_cp0_hpcp_csr.v
add_fileset_file aq_cp0_info_csr.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_cp0_info_csr.v
add_fileset_file aq_cp0_iui.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_cp0_iui.v
add_fileset_file aq_cp0_lpmd.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_cp0_lpmd.v
add_fileset_file aq_cp0_prtc_csr.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_cp0_prtc_csr.v
add_fileset_file aq_cp0_regs.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_cp0_regs.v
add_fileset_file aq_cp0_rst_ctrl.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_cp0_rst_ctrl.v
add_fileset_file aq_cp0_special.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_cp0_special.v
add_fileset_file aq_cp0_top.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_cp0_top.v
add_fileset_file aq_cp0_trap_csr.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_cp0_trap_csr.v
add_fileset_file aq_cp0_vector_inst.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_cp0_vector_inst.v
add_fileset_file aq_cpuio_top.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_cpuio_top.v
add_fileset_file aq_dcache_data_array.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_dcache_data_array.v
add_fileset_file aq_dcache_dirty_array.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_dcache_dirty_array.v
add_fileset_file aq_dcache_tag_array.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_dcache_tag_array.v
add_fileset_file aq_dcache_top.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_dcache_top.v
add_fileset_file aq_dtu_cdc.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_dtu_cdc.v
add_fileset_file aq_dtu_cdc_lvl.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_dtu_cdc_lvl.v
add_fileset_file aq_dtu_cdc_pulse.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_dtu_cdc_pulse.v
add_fileset_file aq_dtu_cfig.h OTHER PATH C906_RTL_FACTORY/gen_rtl/aq_dtu_cfig.h
add_fileset_file aq_dtu_ctrl.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_dtu_ctrl.v
add_fileset_file aq_dtu_dbginfo.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_dtu_dbginfo.v
add_fileset_file aq_dtu_iie_trigger.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_dtu_iie_trigger.v
add_fileset_file aq_dtu_m_iie_all.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_dtu_m_iie_all.v
add_fileset_file aq_dtu_mcontrol.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_dtu_mcontrol.v
add_fileset_file aq_dtu_mcontrol_output_select.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_dtu_mcontrol_output_select.v
add_fileset_file aq_dtu_pcfifo.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_dtu_pcfifo.v
add_fileset_file aq_dtu_top.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_dtu_top.v
add_fileset_file aq_dtu_trigger_module.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_dtu_trigger_module.v
add_fileset_file aq_f_spsram_1024x16.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_f_spsram_1024x16.v
add_fileset_file aq_f_spsram_1024x64.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_f_spsram_1024x64.v
add_fileset_file aq_f_spsram_128x8.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_f_spsram_128x8.v
add_fileset_file aq_f_spsram_2048x32.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_f_spsram_2048x32.v
add_fileset_file aq_f_spsram_256x59.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_f_spsram_256x59.v
add_fileset_file aq_f_spsram_64x58.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_f_spsram_64x58.v
add_fileset_file aq_f_spsram_64x88.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_f_spsram_64x88.v
add_fileset_file aq_f_spsram_64x98.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_f_spsram_64x98.v
add_fileset_file aq_fadd_double_add.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_fadd_double_add.v
add_fileset_file aq_fadd_double_cmp_max.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_fadd_double_cmp_max.v
add_fileset_file aq_fadd_double_dp.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_fadd_double_dp.v
add_fileset_file aq_fadd_double_round.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_fadd_double_round.v
add_fileset_file aq_fadd_double_special.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_fadd_double_special.v
add_fileset_file aq_fadd_double_top.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_fadd_double_top.v
add_fileset_file aq_fadd_lop_s1_sb.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_fadd_lop_s1_sb.v
add_fileset_file aq_fadd_scalar_dp.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_fadd_scalar_dp.v
add_fileset_file aq_fadd_shift_sub_h_double.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_fadd_shift_sub_h_double.v
add_fileset_file aq_fadd_shift_sub_single.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_fadd_shift_sub_single.v
add_fileset_file aq_falu_ctrl.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_falu_ctrl.v
add_fileset_file aq_falu_top.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_falu_top.v
add_fileset_file aq_fcnvt_ctrl.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_fcnvt_ctrl.v
add_fileset_file aq_fcnvt_double.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_fcnvt_double.v
add_fileset_file aq_fcnvt_dtos_d.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_fcnvt_dtos_d.v
add_fileset_file aq_fcnvt_ftoi_d.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_fcnvt_ftoi_d.v
add_fileset_file aq_fcnvt_scalar_dp.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_fcnvt_scalar_dp.v
add_fileset_file aq_fcnvt_top.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_fcnvt_top.v
add_fileset_file aq_fcnvt_xtoh_sh.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_fcnvt_xtoh_sh.v
add_fileset_file aq_fdsu_denorm_shift.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_fdsu_denorm_shift.v
add_fileset_file aq_fdsu_double.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_fdsu_double.v
add_fileset_file aq_fdsu_double_dp.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_fdsu_double_dp.v
add_fileset_file aq_fdsu_pack.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_fdsu_pack.v
add_fileset_file aq_fdsu_prepare.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_fdsu_prepare.v
add_fileset_file aq_fdsu_right_shift.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_fdsu_right_shift.v
add_fileset_file aq_fdsu_round.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_fdsu_round.v
add_fileset_file aq_fdsu_scalar_ctrl.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_fdsu_scalar_ctrl.v
add_fileset_file aq_fdsu_scalar_dp.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_fdsu_scalar_dp.v
add_fileset_file aq_fdsu_special.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_fdsu_special.v
add_fileset_file aq_fdsu_srt.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_fdsu_srt.v
add_fileset_file aq_fdsu_top.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_fdsu_top.v
add_fileset_file aq_fspu_top.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_fspu_top.v
add_fileset_file aq_hpcp_adder_sel.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_hpcp_adder_sel.v
add_fileset_file aq_hpcp_cnt.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_hpcp_cnt.v
add_fileset_file aq_hpcp_cntinten_reg.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_hpcp_cntinten_reg.v
add_fileset_file aq_hpcp_cntof_reg.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_hpcp_cntof_reg.v
add_fileset_file aq_hpcp_event.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_hpcp_event.v
add_fileset_file aq_hpcp_top.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_hpcp_top.v
add_fileset_file aq_idu_cfig.h VERILOG_INCLUDE PATH C906_RTL_FACTORY/gen_rtl/aq_idu_cfig.h
add_fileset_file aq_idu_expand_32.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_idu_expand_32.v
add_fileset_file aq_idu_id_ctrl.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_idu_id_ctrl.v
add_fileset_file aq_idu_id_decd.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_idu_id_decd.v
add_fileset_file aq_idu_id_dp.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_idu_id_dp.v
add_fileset_file aq_idu_id_gpr.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_idu_id_gpr.v
add_fileset_file aq_idu_id_gpr_gated_reg.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_idu_id_gpr_gated_reg.v
add_fileset_file aq_idu_id_split.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_idu_id_split.v
add_fileset_file aq_idu_id_wbt.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_idu_id_wbt.v
add_fileset_file aq_idu_id_wbt_entry.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_idu_id_wbt_entry.v
add_fileset_file aq_idu_top.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_idu_top.v
add_fileset_file aq_ifu_bht.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_ifu_bht.v
add_fileset_file aq_ifu_bht_array.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_ifu_bht_array.v
add_fileset_file aq_ifu_btb.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_ifu_btb.v
add_fileset_file aq_ifu_btb_entry.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_ifu_btb_entry.v
add_fileset_file aq_ifu_ctrl.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_ifu_ctrl.v
add_fileset_file aq_ifu_ibuf.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_ifu_ibuf.v
add_fileset_file aq_ifu_ibuf_entry.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_ifu_ibuf_entry.v
add_fileset_file aq_ifu_ibuf_pop_entry.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_ifu_ibuf_pop_entry.v
add_fileset_file aq_ifu_icache.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_ifu_icache.v
add_fileset_file aq_ifu_icache_data_array.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_ifu_icache_data_array.v
add_fileset_file aq_ifu_icache_tag_array.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_ifu_icache_tag_array.v
add_fileset_file aq_ifu_ipack.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_ifu_ipack.v
add_fileset_file aq_ifu_ipack_entry.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_ifu_ipack_entry.v
add_fileset_file aq_ifu_pcgen.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_ifu_pcgen.v
add_fileset_file aq_ifu_pre_decd.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_ifu_pre_decd.v
add_fileset_file aq_ifu_pred.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_ifu_pred.v
add_fileset_file aq_ifu_ras.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_ifu_ras.v
add_fileset_file aq_ifu_ras_entry.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_ifu_ras_entry.v
add_fileset_file aq_ifu_top.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_ifu_top.v
add_fileset_file aq_ifu_vec.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_ifu_vec.v
add_fileset_file aq_iu_addr_gen.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_iu_addr_gen.v
add_fileset_file aq_iu_alu.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_iu_alu.v
add_fileset_file aq_iu_bju.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_iu_bju.v
add_fileset_file aq_iu_div.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_iu_div.v
add_fileset_file aq_iu_div_shift2_kernel.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_iu_div_shift2_kernel.v
add_fileset_file aq_iu_mul.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_iu_mul.v
add_fileset_file aq_iu_top.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_iu_top.v
add_fileset_file aq_left_shift_64.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_left_shift_64.v
add_fileset_file aq_lsu_ag.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_lsu_ag.v
add_fileset_file aq_lsu_amo_alu.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_lsu_amo_alu.v
add_fileset_file aq_lsu_amr.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_lsu_amr.v
add_fileset_file aq_lsu_arb.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_lsu_arb.v
add_fileset_file aq_lsu_cfig.h VERILOG_INCLUDE PATH C906_RTL_FACTORY/gen_rtl/aq_lsu_cfig.h
add_fileset_file aq_lsu_dc.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_lsu_dc.v
add_fileset_file aq_lsu_dtif.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_lsu_dtif.v
add_fileset_file aq_lsu_icc.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_lsu_icc.v
add_fileset_file aq_lsu_lfb.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_lsu_lfb.v
add_fileset_file aq_lsu_lfb_entry.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_lsu_lfb_entry.v
add_fileset_file aq_lsu_lm.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_lsu_lm.v
add_fileset_file aq_lsu_mcic.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_lsu_mcic.v
add_fileset_file aq_lsu_pfb.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_lsu_pfb.v
add_fileset_file aq_lsu_pfb_top.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_lsu_pfb_top.v
add_fileset_file aq_lsu_rdl.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_lsu_rdl.v
add_fileset_file aq_lsu_stb.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_lsu_stb.v
add_fileset_file aq_lsu_stb_entry.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_lsu_stb_entry.v
add_fileset_file aq_lsu_top.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_lsu_top.v
add_fileset_file aq_lsu_vb.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_lsu_vb.v
add_fileset_file aq_mmu_arb.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_mmu_arb.v
add_fileset_file aq_mmu_jtlb.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_mmu_jtlb.v
add_fileset_file aq_mmu_jtlb_data_array.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_mmu_jtlb_data_array.v
add_fileset_file aq_mmu_jtlb_tag_array.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_mmu_jtlb_tag_array.v
add_fileset_file aq_mmu_plru.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_mmu_plru.v
add_fileset_file aq_mmu_ptw.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_mmu_ptw.v
add_fileset_file aq_mmu_regs.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_mmu_regs.v
add_fileset_file aq_mmu_sysmap.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_mmu_sysmap.v
add_fileset_file aq_mmu_sysmap_hit.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_mmu_sysmap_hit.v
add_fileset_file aq_mmu_tlboper.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_mmu_tlboper.v
add_fileset_file aq_mmu_top.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_mmu_top.v
add_fileset_file aq_mmu_utlb.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_mmu_utlb.v
add_fileset_file aq_mmu_utlb_entry.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_mmu_utlb_entry.v
add_fileset_file aq_mmu_utlb_top.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_mmu_utlb_top.v
add_fileset_file aq_mp_clk_top.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_mp_clk_top.v
add_fileset_file aq_mp_rst_top.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_mp_rst_top.v
add_fileset_file aq_pmp_acc.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_pmp_acc.v
add_fileset_file aq_pmp_comp_hit.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_pmp_comp_hit.v
add_fileset_file aq_pmp_regs.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_pmp_regs.v
add_fileset_file aq_pmp_top.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_pmp_top.v
add_fileset_file aq_prio.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_prio.v
add_fileset_file aq_rtu_ctrl.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_rtu_ctrl.v
add_fileset_file aq_rtu_dp.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_rtu_dp.v
add_fileset_file aq_rtu_int.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_rtu_int.v
add_fileset_file aq_rtu_rbus.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_rtu_rbus.v
add_fileset_file aq_rtu_retire.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_rtu_retire.v
add_fileset_file aq_rtu_top.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_rtu_top.v
add_fileset_file aq_rtu_wb.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_rtu_wb.v
add_fileset_file aq_spsram_1024x16.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_spsram_1024x16.v
add_fileset_file aq_spsram_1024x64.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_spsram_1024x64.v
add_fileset_file aq_spsram_128x8.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_spsram_128x8.v
add_fileset_file aq_spsram_2048x32.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_spsram_2048x32.v
add_fileset_file aq_spsram_256x59.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_spsram_256x59.v
add_fileset_file aq_spsram_64x58.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_spsram_64x58.v
add_fileset_file aq_spsram_64x88.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_spsram_64x88.v
add_fileset_file aq_spsram_64x98.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_spsram_64x98.v
add_fileset_file aq_sysio_kid.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_sysio_kid.v
add_fileset_file aq_sysio_top.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_sysio_top.v
add_fileset_file aq_top.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_top.v
add_fileset_file aq_vdsp_64_bit_ff1.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_vdsp_64_bit_ff1.v
add_fileset_file aq_vdsp_8_bit_ff1.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_vdsp_8_bit_ff1.v
add_fileset_file aq_vfmau_ctrl.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_vfmau_ctrl.v
add_fileset_file aq_vfmau_dp.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_vfmau_dp.v
add_fileset_file aq_vfmau_frac_mult.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_vfmau_frac_mult.v
add_fileset_file aq_vfmau_frac_shift_double.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_vfmau_frac_shift_double.v
add_fileset_file aq_vfmau_lza_double.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_vfmau_lza_double.v
add_fileset_file aq_vfmau_mult.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_vfmau_mult.v
add_fileset_file aq_vfmau_mult_double.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_vfmau_mult_double.v
add_fileset_file aq_vfmau_multiplier_53x27_partial_fpga_infer.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_vfmau_multiplier_53x27_partial_fpga_infer.v
add_fileset_file aq_vfmau_special_judge_double.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_vfmau_special_judge_double.v
add_fileset_file aq_vfmau_top.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_vfmau_top.v
add_fileset_file aq_vidu_top.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_vidu_top.v
add_fileset_file aq_vidu_vid_ctrl_fp.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_vidu_vid_ctrl_fp.v
add_fileset_file aq_vidu_vid_dp_fp.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_vidu_vid_dp_fp.v
add_fileset_file aq_vidu_vid_gpr_fp.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_vidu_vid_gpr_fp.v
add_fileset_file aq_vidu_vid_gpr_reg_fp.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_vidu_vid_gpr_reg_fp.v
add_fileset_file aq_vidu_vid_split_fp.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_vidu_vid_split_fp.v
add_fileset_file aq_vidu_vid_wbt.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_vidu_vid_wbt.v
add_fileset_file aq_vidu_vid_wbt_entry.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_vidu_vid_wbt_entry.v
add_fileset_file aq_vlsu_data_trans.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_vlsu_data_trans.v
add_fileset_file aq_vlsu_ld_align_buffer.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_vlsu_ld_align_buffer.v
add_fileset_file aq_vlsu_lsu_if.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_vlsu_lsu_if.v
add_fileset_file aq_vlsu_rot_data.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_vlsu_rot_data.v
add_fileset_file aq_vlsu_st_align_buffer.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_vlsu_st_align_buffer.v
add_fileset_file aq_vlsu_top.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_vlsu_top.v
add_fileset_file aq_vlsu_vtb.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_vlsu_vtb.v
add_fileset_file aq_vlsu_vtb_entry.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_vlsu_vtb_entry.v
add_fileset_file aq_vpu_fwd_wb_rbus.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_vpu_fwd_wb_rbus.v
add_fileset_file aq_vpu_group_unit.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_vpu_group_unit.v
add_fileset_file aq_vpu_srcv_type.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_vpu_srcv_type.v
add_fileset_file aq_vpu_top.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_vpu_top.v
add_fileset_file aq_vpu_viq_dp.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/aq_vpu_viq_dp.v
add_fileset_file clint_func.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/clint_func.v
add_fileset_file clint_top.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/clint_top.v
add_fileset_file cpu_cfig.h VERILOG_INCLUDE PATH C906_RTL_FACTORY/gen_rtl/cpu_cfig.h
add_fileset_file csky_apb_1tox_matrix.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/csky_apb_1tox_matrix.v
add_fileset_file fpga_ram.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/fpga_ram.v
add_fileset_file gated_clk_cell.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/gated_clk_cell.v
add_fileset_file mp_top_golden_port.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/mp_top_golden_port.v
add_fileset_file multiplier_33x33_partial_fpga_infer.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/multiplier_33x33_partial_fpga_infer.v
add_fileset_file openC906.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/openC906.v TOP_LEVEL_FILE
add_fileset_file plic_32to1_arb.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/plic_32to1_arb.v
add_fileset_file plic_arb_ctrl.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/plic_arb_ctrl.v
add_fileset_file plic_ctrl.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/plic_ctrl.v
add_fileset_file plic_granu2_arb.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/plic_granu2_arb.v
add_fileset_file plic_granu_arb.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/plic_granu_arb.v
add_fileset_file plic_hart_arb.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/plic_hart_arb.v
add_fileset_file plic_hreg_busif.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/plic_hreg_busif.v
add_fileset_file plic_int_kid.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/plic_int_kid.v
add_fileset_file plic_kid_busif.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/plic_kid_busif.v
add_fileset_file plic_top.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/plic_top.v
add_fileset_file sync_level2level.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/sync_level2level.v
add_fileset_file sysmap.h VERILOG_INCLUDE PATH C906_RTL_FACTORY/gen_rtl/sysmap.h
add_fileset_file tdt_dm.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/tdt_dm.v
add_fileset_file tdt_dm_pulse_sync.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/tdt_dm_pulse_sync.v
add_fileset_file tdt_dm_sync_dff.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/tdt_dm_sync_dff.v
add_fileset_file tdt_dm_top.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/tdt_dm_top.v
add_fileset_file tdt_sba_axi.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/tdt_sba_axi.v
add_fileset_file tdt_top.v VERILOG PATH C906_RTL_FACTORY/gen_rtl/tdt_top.v
add_fileset_file tdt_define.h VERILOG_INCLUDE PATH C906_RTL_FACTORY/gen_rtl/tdt_define.h
add_fileset_file tdt_dmi_define.h VERILOG_INCLUDE PATH C906_RTL_FACTORY/gen_rtl/tdt_dmi_define.h


# 
# parameters
# 


# 
# display items
# 


# 
# connection point cpuclk
# 
add_interface cpuclk clock end
set_interface_property cpuclk ENABLED true
set_interface_property cpuclk EXPORT_OF ""
set_interface_property cpuclk PORT_NAME_MAP ""
set_interface_property cpuclk CMSIS_SVD_VARIABLES ""
set_interface_property cpuclk SVD_ADDRESS_GROUP ""
set_interface_property cpuclk IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property cpuclk SV_INTERFACE_TYPE ""
set_interface_property cpuclk SV_INTERFACE_MODPORT_TYPE ""

add_interface_port cpuclk pll_core_cpuclk clk Input 1


# 
# connection point apbclk
# 
add_interface apbclk clock end
set_interface_property apbclk ENABLED true
set_interface_property apbclk EXPORT_OF ""
set_interface_property apbclk PORT_NAME_MAP ""
set_interface_property apbclk CMSIS_SVD_VARIABLES ""
set_interface_property apbclk SVD_ADDRESS_GROUP ""
set_interface_property apbclk IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property apbclk SV_INTERFACE_TYPE ""
set_interface_property apbclk SV_INTERFACE_MODPORT_TYPE ""

add_interface_port apbclk sys_apb_clk clk Input 1


# 
# connection point apbrst
# 
add_interface apbrst reset end
set_interface_property apbrst associatedClock apbclk
set_interface_property apbrst synchronousEdges DEASSERT
set_interface_property apbrst ENABLED true
set_interface_property apbrst EXPORT_OF ""
set_interface_property apbrst PORT_NAME_MAP ""
set_interface_property apbrst CMSIS_SVD_VARIABLES ""
set_interface_property apbrst SVD_ADDRESS_GROUP ""
set_interface_property apbrst IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property apbrst SV_INTERFACE_TYPE ""
set_interface_property apbrst SV_INTERFACE_MODPORT_TYPE ""

add_interface_port apbrst sys_apb_rst_b reset_n Input 1


# 
# connection point dmi
# 
add_interface dmi apb end
set_interface_property dmi associatedClock apbclk
set_interface_property dmi associatedReset apbrst
set_interface_property dmi ENABLED true
set_interface_property dmi EXPORT_OF ""
set_interface_property dmi PORT_NAME_MAP ""
set_interface_property dmi CMSIS_SVD_VARIABLES ""
set_interface_property dmi SVD_ADDRESS_GROUP ""
set_interface_property dmi IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property dmi SV_INTERFACE_TYPE ""
set_interface_property dmi SV_INTERFACE_MODPORT_TYPE ""

add_interface_port dmi tdt_dmi_paddr paddr Input 12
add_interface_port dmi tdt_dmi_penable penable Input 1
add_interface_port dmi tdt_dmi_prdata prdata Output 32
add_interface_port dmi tdt_dmi_pready pready Output 1
add_interface_port dmi tdt_dmi_psel psel Input 1
add_interface_port dmi tdt_dmi_pslverr pslverr Output 1
add_interface_port dmi tdt_dmi_pwdata pwdata Input 32
add_interface_port dmi tdt_dmi_pwrite pwrite Input 1


# 
# connection point clken
# 
add_interface clken conduit end
set_interface_property clken associatedClock cpuclk
set_interface_property clken associatedReset ""
set_interface_property clken ENABLED true
set_interface_property clken EXPORT_OF ""
set_interface_property clken PORT_NAME_MAP ""
set_interface_property clken CMSIS_SVD_VARIABLES ""
set_interface_property clken SVD_ADDRESS_GROUP ""
set_interface_property clken IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property clken SV_INTERFACE_TYPE ""
set_interface_property clken SV_INTERFACE_MODPORT_TYPE ""

add_interface_port clken axim_clk_en clk_en Input 1


# 
# connection point monitor
# 
add_interface monitor conduit end
set_interface_property monitor associatedClock cpuclk
set_interface_property monitor associatedReset ""
set_interface_property monitor ENABLED true
set_interface_property monitor EXPORT_OF ""
set_interface_property monitor PORT_NAME_MAP ""
set_interface_property monitor CMSIS_SVD_VARIABLES ""
set_interface_property monitor SVD_ADDRESS_GROUP ""
set_interface_property monitor IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property monitor SV_INTERFACE_TYPE ""
set_interface_property monitor SV_INTERFACE_MODPORT_TYPE ""

add_interface_port monitor core0_pad_halted halted Output 1
add_interface_port monitor core0_pad_lpmd_b lpmd_n Output 2
add_interface_port monitor core0_pad_retire retire Output 1
add_interface_port monitor core0_pad_retire_pc retire_pc Output 40
add_interface_port monitor cpu_debug_port cpu_debug_port Output 1


# 
# connection point main_axi
# 
add_interface main_axi axi4 start
set_interface_property main_axi associatedClock cpuclk
set_interface_property main_axi associatedReset cpurst
set_interface_property main_axi wakeupSignals false
set_interface_property main_axi uniqueIdSupport false
set_interface_property main_axi poison false
set_interface_property main_axi traceSignals false
set_interface_property main_axi isTranslator false
set_interface_property main_axi dataCheck false
set_interface_property main_axi addressCheck false
set_interface_property main_axi securityAttribute false
set_interface_property main_axi userData false
set_interface_property main_axi readIssuingCapability 10
set_interface_property main_axi writeIssuingCapability 16
set_interface_property main_axi combinedIssuingCapability 26
set_interface_property main_axi enableConcurrentSubordinateAccess 0
set_interface_property main_axi noRepeatedIdsBetweenSubordinates 0
set_interface_property main_axi issuesINCRBursts true
set_interface_property main_axi issuesWRAPBursts true
set_interface_property main_axi issuesFIXEDBursts false
set_interface_property main_axi ENABLED true
set_interface_property main_axi EXPORT_OF ""
set_interface_property main_axi PORT_NAME_MAP ""
set_interface_property main_axi CMSIS_SVD_VARIABLES ""
set_interface_property main_axi SVD_ADDRESS_GROUP ""
set_interface_property main_axi IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property main_axi SV_INTERFACE_TYPE ""
set_interface_property main_axi SV_INTERFACE_MODPORT_TYPE ""

add_interface_port main_axi biu_pad_araddr araddr Output 40
add_interface_port main_axi biu_pad_arburst arburst Output 2
add_interface_port main_axi biu_pad_arcache arcache Output 4
add_interface_port main_axi biu_pad_arid arid Output 8
add_interface_port main_axi biu_pad_arlen arlen Output 8
add_interface_port main_axi biu_pad_arlock arlock Output 1
add_interface_port main_axi biu_pad_arprot arprot Output 3
add_interface_port main_axi biu_pad_arsize arsize Output 3
add_interface_port main_axi biu_pad_arvalid arvalid Output 1
add_interface_port main_axi biu_pad_awaddr awaddr Output 40
add_interface_port main_axi biu_pad_awburst awburst Output 2
add_interface_port main_axi biu_pad_awcache awcache Output 4
add_interface_port main_axi biu_pad_awid awid Output 8
add_interface_port main_axi biu_pad_awlen awlen Output 8
add_interface_port main_axi biu_pad_awlock awlock Output 1
add_interface_port main_axi biu_pad_awprot awprot Output 3
add_interface_port main_axi biu_pad_awsize awsize Output 3
add_interface_port main_axi biu_pad_awvalid awvalid Output 1
add_interface_port main_axi biu_pad_bready bready Output 1
add_interface_port main_axi biu_pad_rready rready Output 1
add_interface_port main_axi biu_pad_wdata wdata Output 128
add_interface_port main_axi biu_pad_wlast wlast Output 1
add_interface_port main_axi biu_pad_wstrb wstrb Output 16
add_interface_port main_axi biu_pad_wvalid wvalid Output 1
add_interface_port main_axi pad_biu_arready arready Input 1
add_interface_port main_axi pad_biu_awready awready Input 1
add_interface_port main_axi pad_biu_bid bid Input 8
add_interface_port main_axi pad_biu_bresp bresp Input 2
add_interface_port main_axi pad_biu_bvalid bvalid Input 1
add_interface_port main_axi pad_biu_rdata rdata Input 128
add_interface_port main_axi pad_biu_rid rid Input 8
add_interface_port main_axi pad_biu_rlast rlast Input 1
add_interface_port main_axi pad_biu_rresp rresp Input 2
add_interface_port main_axi pad_biu_rvalid rvalid Input 1
add_interface_port main_axi pad_biu_wready wready Input 1


# 
# connection point dm_axi
# 
add_interface dm_axi axi4 start
set_interface_property dm_axi associatedClock cpuclk
set_interface_property dm_axi associatedReset cpurst
set_interface_property dm_axi wakeupSignals false
set_interface_property dm_axi uniqueIdSupport false
set_interface_property dm_axi poison false
set_interface_property dm_axi traceSignals false
set_interface_property dm_axi isTranslator false
set_interface_property dm_axi dataCheck false
set_interface_property dm_axi addressCheck false
set_interface_property dm_axi securityAttribute false
set_interface_property dm_axi userData false
set_interface_property dm_axi readIssuingCapability 1
set_interface_property dm_axi writeIssuingCapability 1
set_interface_property dm_axi combinedIssuingCapability 1
set_interface_property dm_axi enableConcurrentSubordinateAccess 0
set_interface_property dm_axi noRepeatedIdsBetweenSubordinates 0
set_interface_property dm_axi issuesINCRBursts true
set_interface_property dm_axi issuesWRAPBursts false
set_interface_property dm_axi issuesFIXEDBursts false
set_interface_property dm_axi ENABLED true
set_interface_property dm_axi EXPORT_OF ""
set_interface_property dm_axi PORT_NAME_MAP ""
set_interface_property dm_axi CMSIS_SVD_VARIABLES ""
set_interface_property dm_axi SVD_ADDRESS_GROUP ""
set_interface_property dm_axi IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property dm_axi SV_INTERFACE_TYPE ""
set_interface_property dm_axi SV_INTERFACE_MODPORT_TYPE ""

add_interface_port dm_axi tdt_dm_pad_araddr araddr Output 40
add_interface_port dm_axi tdt_dm_pad_arburst arburst Output 2
add_interface_port dm_axi tdt_dm_pad_arcache arcache Output 4
add_interface_port dm_axi tdt_dm_pad_arid arid Output 4
add_interface_port dm_axi tdt_dm_pad_arlen arlen Output 8
add_interface_port dm_axi tdt_dm_pad_arlock arlock Output 1
add_interface_port dm_axi tdt_dm_pad_arprot arprot Output 3
add_interface_port dm_axi tdt_dm_pad_arsize arsize Output 3
add_interface_port dm_axi tdt_dm_pad_arvalid arvalid Output 1
add_interface_port dm_axi tdt_dm_pad_awaddr awaddr Output 40
add_interface_port dm_axi tdt_dm_pad_awburst awburst Output 2
add_interface_port dm_axi tdt_dm_pad_awcache awcache Output 4
add_interface_port dm_axi tdt_dm_pad_awid awid Output 4
add_interface_port dm_axi tdt_dm_pad_awlen awlen Output 8
add_interface_port dm_axi tdt_dm_pad_awlock awlock Output 1
add_interface_port dm_axi tdt_dm_pad_awprot awprot Output 3
add_interface_port dm_axi tdt_dm_pad_awsize awsize Output 3
add_interface_port dm_axi tdt_dm_pad_awvalid awvalid Output 1
add_interface_port dm_axi tdt_dm_pad_bready bready Output 1
add_interface_port dm_axi tdt_dm_pad_rready rready Output 1
add_interface_port dm_axi tdt_dm_pad_wdata wdata Output 128
add_interface_port dm_axi tdt_dm_pad_wlast wlast Output 1
add_interface_port dm_axi tdt_dm_pad_wstrb wstrb Output 16
add_interface_port dm_axi tdt_dm_pad_wvalid wvalid Output 1
add_interface_port dm_axi pad_tdt_dm_arready arready Input 1
add_interface_port dm_axi pad_tdt_dm_awready awready Input 1
add_interface_port dm_axi pad_tdt_dm_bid bid Input 4
add_interface_port dm_axi pad_tdt_dm_bresp bresp Input 2
add_interface_port dm_axi pad_tdt_dm_bvalid bvalid Input 1
add_interface_port dm_axi pad_tdt_dm_rdata rdata Input 128
add_interface_port dm_axi pad_tdt_dm_rid rid Input 4
add_interface_port dm_axi pad_tdt_dm_rlast rlast Input 1
add_interface_port dm_axi pad_tdt_dm_rresp rresp Input 2
add_interface_port dm_axi pad_tdt_dm_rvalid rvalid Input 1
add_interface_port dm_axi pad_tdt_dm_wready wready Input 1


# 
# connection point hartreset
# 
add_interface hartreset reset start
set_interface_property hartreset associatedClock apbclk
set_interface_property hartreset associatedDirectReset apbrst
set_interface_property hartreset associatedResetSinks apbrst
set_interface_property hartreset synchronousEdges DEASSERT
set_interface_property hartreset ENABLED true
set_interface_property hartreset EXPORT_OF ""
set_interface_property hartreset PORT_NAME_MAP ""
set_interface_property hartreset CMSIS_SVD_VARIABLES ""
set_interface_property hartreset SVD_ADDRESS_GROUP ""
set_interface_property hartreset IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property hartreset SV_INTERFACE_TYPE ""
set_interface_property hartreset SV_INTERFACE_MODPORT_TYPE ""

add_interface_port hartreset tdt_dm_pad_hartreset_n reset_n Output 1


# 
# connection point ndmreset
# 
add_interface ndmreset reset start
set_interface_property ndmreset associatedClock apbclk
set_interface_property ndmreset associatedDirectReset apbrst
set_interface_property ndmreset associatedResetSinks apbrst
set_interface_property ndmreset synchronousEdges DEASSERT
set_interface_property ndmreset ENABLED true
set_interface_property ndmreset EXPORT_OF ""
set_interface_property ndmreset PORT_NAME_MAP ""
set_interface_property ndmreset CMSIS_SVD_VARIABLES ""
set_interface_property ndmreset SVD_ADDRESS_GROUP ""
set_interface_property ndmreset IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property ndmreset SV_INTERFACE_TYPE ""
set_interface_property ndmreset SV_INTERFACE_MODPORT_TYPE ""

add_interface_port ndmreset tdt_dm_pad_ndmreset_n reset_n Output 1


# 
# connection point dft
# 
add_interface dft conduit end
set_interface_property dft associatedClock ""
set_interface_property dft associatedReset ""
set_interface_property dft ENABLED true
set_interface_property dft EXPORT_OF ""
set_interface_property dft PORT_NAME_MAP ""
set_interface_property dft CMSIS_SVD_VARIABLES ""
set_interface_property dft SVD_ADDRESS_GROUP ""
set_interface_property dft IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property dft SV_INTERFACE_TYPE ""
set_interface_property dft SV_INTERFACE_MODPORT_TYPE ""

add_interface_port dft pad_yy_dft_clk_rst_b dft_clk_rst_b Input 1
add_interface_port dft pad_yy_icg_scan_en icg_scan_en Input 1
add_interface_port dft pad_yy_mbist_mode mbist_mode Input 1
add_interface_port dft pad_yy_scan_enable scan_enable Input 1
add_interface_port dft pad_yy_scan_mode scan_mode Input 1
add_interface_port dft pad_yy_scan_rst_b scan_rst_n Input 1


# 
# connection point cpurst
# 
add_interface cpurst reset end
set_interface_property cpurst associatedClock cpuclk
set_interface_property cpurst synchronousEdges DEASSERT
set_interface_property cpurst ENABLED true
set_interface_property cpurst EXPORT_OF ""
set_interface_property cpurst PORT_NAME_MAP ""
set_interface_property cpurst CMSIS_SVD_VARIABLES ""
set_interface_property cpurst SVD_ADDRESS_GROUP ""
set_interface_property cpurst IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property cpurst SV_INTERFACE_TYPE ""
set_interface_property cpurst SV_INTERFACE_MODPORT_TYPE ""

add_interface_port cpurst pad_cpu_rst_b reset_n Input 1


# 
# connection point core_unavail
# 
add_interface core_unavail conduit end
set_interface_property core_unavail associatedClock cpuclk
set_interface_property core_unavail associatedReset ""
set_interface_property core_unavail ENABLED true
set_interface_property core_unavail EXPORT_OF ""
set_interface_property core_unavail PORT_NAME_MAP ""
set_interface_property core_unavail CMSIS_SVD_VARIABLES ""
set_interface_property core_unavail SVD_ADDRESS_GROUP ""
set_interface_property core_unavail IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property core_unavail SV_INTERFACE_TYPE ""
set_interface_property core_unavail SV_INTERFACE_MODPORT_TYPE ""

add_interface_port core_unavail pad_tdt_dm_core_unavail core_unavail Input 1


# 
# connection point irq
# 
add_interface irq interrupt start
set_interface_property irq associatedClock cpuclk
set_interface_property irq associatedReset cpurst
set_interface_property irq irqScheme INDIVIDUAL_REQUESTS
set_interface_property irq ENABLED true
set_interface_property irq EXPORT_OF ""
set_interface_property irq PORT_NAME_MAP ""
set_interface_property irq CMSIS_SVD_VARIABLES ""
set_interface_property irq SVD_ADDRESS_GROUP ""
set_interface_property irq IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property irq SV_INTERFACE_TYPE ""
set_interface_property irq SV_INTERFACE_MODPORT_TYPE ""

add_interface_port irq pad_plic_int_vld irq Input 240


# 
# connection point cfg
# 
add_interface cfg conduit end
set_interface_property cfg associatedClock cpuclk
set_interface_property cfg associatedReset ""
set_interface_property cfg ENABLED true
set_interface_property cfg EXPORT_OF ""
set_interface_property cfg PORT_NAME_MAP ""
set_interface_property cfg CMSIS_SVD_VARIABLES ""
set_interface_property cfg SVD_ADDRESS_GROUP ""
set_interface_property cfg IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property cfg SV_INTERFACE_TYPE ""
set_interface_property cfg SV_INTERFACE_MODPORT_TYPE ""

add_interface_port cfg pad_plic_int_cfg int_cfg Input 240
add_interface_port cfg pad_cpu_apb_base apb_base Input 40
add_interface_port cfg pad_cpu_rvba rvba Input 40


# 
# connection point counter
# 
add_interface counter conduit end
set_interface_property counter associatedClock cpuclk
set_interface_property counter associatedReset ""
set_interface_property counter ENABLED true
set_interface_property counter EXPORT_OF ""
set_interface_property counter PORT_NAME_MAP ""
set_interface_property counter CMSIS_SVD_VARIABLES ""
set_interface_property counter SVD_ADDRESS_GROUP ""
set_interface_property counter IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property counter SV_INTERFACE_TYPE ""
set_interface_property counter SV_INTERFACE_MODPORT_TYPE ""

add_interface_port counter pad_cpu_sys_cnt sys_cnt Input 64

